jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build -x docs -x distTar -x distZip
    - continue-on-error: true
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      name: Build release jar
      run: "case \"${GITHUB_EVENT_NAME}\" in\n  \"pull_request\")\n    ./gradlew buildReleaseJar\
        \ -PprereleaseTag=\"PR.${PR_NUMBER}\"\n    ;;\n  \"push\")\n    ./gradlew\
        \ buildReleaseJar -PprereleaseTag=\"SNAPSHOT\"\n    ;;\n  *)\n    ./gradlew\
        \ buildReleaseJar\n    ;;\nesac\n"
    - continue-on-error: true
      name: Upload build
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Chunky Build
        path: build/installer
    - continue-on-error: true
      name: Upload build
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Chunky Core
        path: build/chunky-core-*.jar
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
